/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BizHaqimizdaRouteImport } from './routes/biz-haqimizda'
import { Route as MaqolalarIndexRouteImport } from './routes/maqolalar.index'
import { Route as MaqolalarSlugRouteImport } from './routes/maqolalar.$slug'
import { Route as MavzularIndexRouteImport } from './routes/mavzular.index'
import { Route as MavzularThemeRouteImport } from './routes/mavzular.$theme'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated.admin.subscribers'
import { Route as AuthenticatedAdminArticlesIndexRouteImport } from './routes/_authenticated.admin.articles.index'
import { Route as AuthenticatedAdminArticlesNewRouteImport } from './routes/_authenticated.admin.articles.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BizHaqimizdaRoute = BizHaqimizdaRouteImport.update({
  id: '/biz-haqimizda',
  path: '/biz-haqimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const MaqolalarIndexRoute = MaqolalarIndexRouteImport.update({
  id: '/maqolalar/',
  path: '/maqolalar/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaqolalarSlugRoute = MaqolalarSlugRouteImport.update({
  id: '/maqolalar/$slug',
  path: '/maqolalar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MavzularIndexRoute = MavzularIndexRouteImport.update({
  id: '/mavzular/',
  path: '/mavzular/',
  getParentRoute: () => rootRouteImport,
} as any)
const MavzularThemeRoute = MavzularThemeRouteImport.update({
  id: '/$theme',
  path: '/$theme',
  getParentRoute: () => MavzularRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/admin/subscribers',
    path: '/admin/subscribers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminArticlesIndexRoute =
  AuthenticatedAdminArticlesIndexRouteImport.update({
    id: '/admin/articles/',
    path: '/admin/articles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminArticlesNewRoute =
  AuthenticatedAdminArticlesNewRouteImport.update({
    id: '/admin/articles/new',
    path: '/admin/articles/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biz-haqimizda': typeof BizHaqimizdaRoute
  '/maqolalar/$slug': typeof MaqolalarSlugRoute
  '/mavzular/$theme': typeof MavzularThemeRoute
  '/maqolalar/': typeof MaqolalarIndexRoute
  '/mavzular/': typeof MavzularIndexRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/articles/new': typeof AuthenticatedAdminArticlesNewRoute
  '/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biz-haqimizda': typeof BizHaqimizdaRoute
  '/maqolalar/$slug': typeof MaqolalarSlugRoute
  '/mavzular/$theme': typeof MavzularThemeRoute
  '/maqolalar': typeof MaqolalarIndexRoute
  '/mavzular': typeof MavzularIndexRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/articles/new': typeof AuthenticatedAdminArticlesNewRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/biz-haqimizda': typeof BizHaqimizdaRoute
  '/maqolalar/$slug': typeof MaqolalarSlugRoute
  '/mavzular/$theme': typeof MavzularThemeRoute
  '/maqolalar/': typeof MaqolalarIndexRoute
  '/mavzular/': typeof MavzularIndexRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/articles/new': typeof AuthenticatedAdminArticlesNewRoute
  '/_authenticated/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biz-haqimizda'
    | '/maqolalar/$slug'
    | '/mavzular/$theme'
    | '/maqolalar/'
    | '/mavzular/'
    | '/admin/subscribers'
    | '/admin/'
    | '/admin/articles/new'
    | '/admin/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biz-haqimizda'
    | '/maqolalar/$slug'
    | '/mavzular/$theme'
    | '/maqolalar'
    | '/mavzular'
    | '/admin/subscribers'
    | '/admin'
    | '/admin/articles/new'
    | '/admin/articles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/biz-haqimizda'
    | '/maqolalar/$slug'
    | '/mavzular/$theme'
    | '/maqolalar/'
    | '/mavzular/'
    | '/_authenticated/admin/subscribers'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/articles/new'
    | '/_authenticated/admin/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BizHaqimizdaRoute: typeof BizHaqimizdaRoute
  MaqolalarSlugRoute: typeof MaqolalarSlugRoute
  MaqolalarIndexRoute: typeof MaqolalarIndexRoute
  MavzularIndexRoute: typeof MavzularIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz-haqimizda': {
      id: '/biz-haqimizda'
      path: '/biz-haqimizda'
      fullPath: '/biz-haqimizda'
      preLoaderRoute: typeof BizHaqimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maqolalar/': {
      id: '/maqolalar/'
      path: '/maqolalar'
      fullPath: '/maqolalar/'
      preLoaderRoute: typeof MaqolalarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maqolalar/$slug': {
      id: '/maqolalar/$slug'
      path: '/maqolalar/$slug'
      fullPath: '/maqolalar/$slug'
      preLoaderRoute: typeof MaqolalarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mavzular/': {
      id: '/mavzular/'
      path: '/mavzular'
      fullPath: '/mavzular/'
      preLoaderRoute: typeof MavzularIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mavzular/$theme': {
      id: '/mavzular/$theme'
      path: '/$theme'
      fullPath: '/mavzular/$theme'
      preLoaderRoute: typeof MavzularThemeRouteImport
      parentRoute: typeof MavzularRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/articles/': {
      id: '/_authenticated/admin/articles/'
      path: '/admin/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/articles/new': {
      id: '/_authenticated/admin/articles/new'
      path: '/admin/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AuthenticatedAdminArticlesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminArticlesNewRoute: typeof AuthenticatedAdminArticlesNewRoute
  AuthenticatedAdminArticlesIndexRoute: typeof AuthenticatedAdminArticlesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminArticlesNewRoute: AuthenticatedAdminArticlesNewRoute,
  AuthenticatedAdminArticlesIndexRoute: AuthenticatedAdminArticlesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BizHaqimizdaRoute: BizHaqimizdaRoute,
  MaqolalarSlugRoute: MaqolalarSlugRoute,
  MaqolalarIndexRoute: MaqolalarIndexRoute,
  MavzularIndexRoute: MavzularIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
